
export const loginUser = `<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:UserClientResponse xmlns:ns2="http://user.soap.xml">
            <ns2:id>752</ns2:id>
            <ns2:idUser>3102</ns2:idUser>
            <ns2:idEstacao>1</ns2:idEstacao>
            <ns2:dadosUser>
                <ns2:id>3102</ns2:id>
                <ns2:password>240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9</ns2:password>
                <ns2:nome>Sillk</ns2:nome>
                <ns2:sobrenome>Manuel</ns2:sobrenome>
                <ns2:genero>Masculino</ns2:genero>
                <ns2:BI>001456237</ns2:BI>
                <ns2:email>silk@bs.com</ns2:email>
                <ns2:telefone>99999999</ns2:telefone>
                <ns2:foto/>
                <ns2:tipo>2</ns2:tipo>
                <ns2:token>eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzaWxrQGJzLmNvbSIsImlzcyI6InNlcnZlciIsImV4cCI6MTcyMjk2OTA3M30.U3wiiFAzUf6InySqhIGTAAX3tNfiJEmnGAl4tEoHYkc</ns2:token>
            </ns2:dadosUser>
            <ns2:erro>false</ns2:erro>
            <ns2:mensagem>Login efectuado com sucesso!!</ns2:mensagem>
        </ns2:UserClientResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`


export const allAdmin = `<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:GetAllAdmResponse xmlns:ns2="http://user.soap.xml">
            <ns2:estado>true</ns2:estado>
            <ns2:mensagem>Sucesso ao pegar todos usuários administrativos</ns2:mensagem>
            <ns2:administradores>
                <ns2:id>402</ns2:id>
                <ns2:idUser>2205</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2205</ns2:id>
                    <ns2:nome>Ruben</ns2:nome>
                    <ns2:sobrenome>Adm</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>123456789</ns2:BI>
                    <ns2:email>a@example.com</ns2:email>
                    <ns2:telefone>+5511999999999</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>403</ns2:id>
                <ns2:idUser>2207</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2207</ns2:id>
                    <ns2:nome>Ruben</ns2:nome>
                    <ns2:sobrenome>Adm</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>123456789</ns2:BI>
                    <ns2:email>a1@example.com</ns2:email>
                    <ns2:telefone>+5511999999999</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>502</ns2:id>
                <ns2:idUser>2402</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2402</ns2:id>
                    <ns2:nome>Ruben</ns2:nome>
                    <ns2:sobrenome>Adm</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>123456789</ns2:BI>
                    <ns2:email>a3@example.com</ns2:email>
                    <ns2:telefone>+5511999999999</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>552</ns2:id>
                <ns2:idUser>2452</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2452</ns2:id>
                    <ns2:nome>Ruben</ns2:nome>
                    <ns2:sobrenome>Rodrigues</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>1111111111111</ns2:BI>
                    <ns2:email>rubenzidane08@gmail.com</ns2:email>
                    <ns2:telefone>937869519</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>553</ns2:id>
                <ns2:idUser>2453</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2453</ns2:id>
                    <ns2:nome>António</ns2:nome>
                    <ns2:sobrenome>António</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>22222222244444</ns2:BI>
                    <ns2:email>aa@gmail.com</ns2:email>
                    <ns2:telefone>912345678</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>554</ns2:id>
                <ns2:idUser>2455</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2455</ns2:id>
                    <ns2:nome>Cristiano </ns2:nome>
                    <ns2:sobrenome>Ronaldo</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>1111111111111</ns2:BI>
                    <ns2:email>cr7@gmail.com</ns2:email>
                    <ns2:telefone>987654321</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>602</ns2:id>
                <ns2:idUser>2502</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2502</ns2:id>
                    <ns2:nome>Design</ns2:nome>
                    <ns2:sobrenome>Designnnn</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>22222222244444</ns2:BI>
                    <ns2:email>design@gmail.com</ns2:email>
                    <ns2:telefone>999999999</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>652</ns2:id>
                <ns2:idUser>2810</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2810</ns2:id>
                    <ns2:nome>The Last</ns2:nome>
                    <ns2:sobrenome>Man</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>22222222244444</ns2:BI>
                    <ns2:email>lastman@gmail.com</ns2:email>
                    <ns2:telefone>912345678</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>653</ns2:id>
                <ns2:idUser>2814</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2814</ns2:id>
                    <ns2:nome>DasZero</ns2:nome>
                    <ns2:sobrenome>Horas</ns2:sobrenome>
                    <ns2:genero>Feminino</ns2:genero>
                    <ns2:BI>096484276HA032</ns2:BI>
                    <ns2:email>dh@gmail.com</ns2:email>
                    <ns2:telefone>937869519</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>654</ns2:id>
                <ns2:idUser>2818</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2818</ns2:id>
                    <ns2:nome>Another </ns2:nome>
                    <ns2:sobrenome>One</ns2:sobrenome>
                    <ns2:genero>Feminino</ns2:genero>
                    <ns2:BI>006754106LA044</ns2:BI>
                    <ns2:email>ao@gmail.com</ns2:email>
                    <ns2:telefone>912345678</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>655</ns2:id>
                <ns2:idUser>2821</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2821</ns2:id>
                    <ns2:nome>Enough</ns2:nome>
                    <ns2:sobrenome>Enough Enough</ns2:sobrenome>
                    <ns2:genero>Feminino</ns2:genero>
                    <ns2:BI>1111111111111</ns2:BI>
                    <ns2:email>eee@gmail.com</ns2:email>
                    <ns2:telefone>912345678</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>656</ns2:id>
                <ns2:idUser>2823</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>2823</ns2:id>
                    <ns2:nome>Huuum</ns2:nome>
                    <ns2:sobrenome>Hum</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>1111111111111</ns2:BI>
                    <ns2:email>hh@gmail.com</ns2:email>
                    <ns2:telefone>937869519</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>702</ns2:id>
                <ns2:idUser>3059</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>3059</ns2:id>
                    <ns2:nome>user</ns2:nome>
                    <ns2:sobrenome>user</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>22222222244444</ns2:BI>
                    <ns2:email>uu@gmail.com</ns2:email>
                    <ns2:telefone>937869519</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
            <ns2:administradores>
                <ns2:id>752</ns2:id>
                <ns2:idUser>3102</ns2:idUser>
                <ns2:idEstacao>0</ns2:idEstacao>
                <ns2:dadosUser>
                    <ns2:id>3102</ns2:id>
                    <ns2:nome>Sillk</ns2:nome>
                    <ns2:sobrenome>Manuel</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>001456237</ns2:BI>
                    <ns2:email>silk@bs.com</ns2:email>
                    <ns2:telefone>99999999</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>2</ns2:tipo>
                </ns2:dadosUser>
                <ns2:erro>false</ns2:erro>
            </ns2:administradores>
        </ns2:GetAllAdmResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`
export const allCiclistas = `
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:GetAllCiclistasResponse xmlns:ns2="http://user.soap.xml">
            <ns2:estado>true</ns2:estado>
            <ns2:mensagem>Sucesso ao pegar todos usuários ciclistas</ns2:mensagem>
            <ns2:ciclistas>
                <ns2:id>902</ns2:id>
                <ns2:idUser>2203</ns2:idUser>
                <ns2:saldo>7.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2203</ns2:id>
                    <ns2:nome>Fennandes</ns2:nome>
                    <ns2:sobrenome>ciclista</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>123456789</ns2:BI>
                    <ns2:email>c@example.com</ns2:email>
                    <ns2:telefone>+5511999999999</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>903</ns2:id>
                <ns2:idUser>2204</ns2:idUser>
                <ns2:saldo>13.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2204</ns2:id>
                    <ns2:nome>Fennandes</ns2:nome>
                    <ns2:sobrenome>ciclista</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>123456789</ns2:BI>
                    <ns2:email>c1@example.com</ns2:email>
                    <ns2:telefone>+5511999999999</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>952</ns2:id>
                <ns2:idUser>2352</ns2:idUser>
                <ns2:saldo>9.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2352</ns2:id>
                    <ns2:nome>Gaspar</ns2:nome>
                    <ns2:sobrenome/>
                    <ns2:genero/>
                    <ns2:BI>0</ns2:BI>
                    <ns2:email>gaspar01@example.com</ns2:email>
                    <ns2:telefone>988798986</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1002</ns2:id>
                <ns2:idUser>2403</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2403</ns2:id>
                    <ns2:nome>Gu</ns2:nome>
                    <ns2:sobrenome/>
                    <ns2:genero/>
                    <ns2:BI>0</ns2:BI>
                    <ns2:email>go@gmail.com</ns2:email>
                    <ns2:telefone>921776688</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1052</ns2:id>
                <ns2:idUser>2552</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2552</ns2:id>
                    <ns2:nome>Andre</ns2:nome>
                    <ns2:sobrenome/>
                    <ns2:genero/>
                    <ns2:BI>0</ns2:BI>
                    <ns2:email>andre01@example.com</ns2:email>
                    <ns2:telefone>989898987</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1102</ns2:id>
                <ns2:idUser>2602</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2602</ns2:id>
                    <ns2:nome>André </ns2:nome>
                    <ns2:sobrenome>David </ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>2024-08-02</ns2:BI>
                    <ns2:email>ad@gmail.com</ns2:email>
                    <ns2:telefone>921025087</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1103</ns2:id>
                <ns2:idUser>2611</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2611</ns2:id>
                    <ns2:nome>André</ns2:nome>
                    <ns2:sobrenome>ciclista</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>123456789</ns2:BI>
                    <ns2:email>c6@example.com</ns2:email>
                    <ns2:telefone>+5511999999999</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1152</ns2:id>
                <ns2:idUser>2652</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2652</ns2:id>
                    <ns2:nome>eces</ns2:nome>
                    <ns2:sobrenome>ranos</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>13243343</ns2:BI>
                    <ns2:email>a@gmail.com</ns2:email>
                    <ns2:telefone>912345678</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1202</ns2:id>
                <ns2:idUser>2702</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2702</ns2:id>
                    <ns2:nome>ana</ns2:nome>
                    <ns2:sobrenome/>
                    <ns2:genero/>
                    <ns2:BI/>
                    <ns2:email>ana@gmail.com</ns2:email>
                    <ns2:telefone>987665544</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1252</ns2:id>
                <ns2:idUser>2752</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2752</ns2:id>
                    <ns2:nome>anabela</ns2:nome>
                    <ns2:sobrenome/>
                    <ns2:genero/>
                    <ns2:BI/>
                    <ns2:email>anabela@example.com</ns2:email>
                    <ns2:telefone>908976567</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1302</ns2:id>
                <ns2:idUser>2805</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2805</ns2:id>
                    <ns2:nome>yyy</ns2:nome>
                    <ns2:sobrenome>ghh</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>ajh@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1303</ns2:id>
                <ns2:idUser>2807</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2807</ns2:id>
                    <ns2:nome>yyy</ns2:nome>
                    <ns2:sobrenome>ghh</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>ajffh@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1304</ns2:id>
                <ns2:idUser>2808</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2808</ns2:id>
                    <ns2:nome>André </ns2:nome>
                    <ns2:sobrenome>Msrcos</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>fg@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1305</ns2:id>
                <ns2:idUser>2811</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2811</ns2:id>
                    <ns2:nome>ass</ns2:nome>
                    <ns2:sobrenome>gf</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>f@gmail.com </ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1306</ns2:id>
                <ns2:idUser>2813</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2813</ns2:id>
                    <ns2:nome>Mauro</ns2:nome>
                    <ns2:sobrenome>Romeu</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>mr@gmail.com </ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1307</ns2:id>
                <ns2:idUser>2815</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2815</ns2:id>
                    <ns2:nome>ggg</ns2:nome>
                    <ns2:sobrenome>gg</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>fy@gmail.com </ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1308</ns2:id>
                <ns2:idUser>2817</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2817</ns2:id>
                    <ns2:nome>ggg</ns2:nome>
                    <ns2:sobrenome>gg</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>fy@gmail.co.ao</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1309</ns2:id>
                <ns2:idUser>2819</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2819</ns2:id>
                    <ns2:nome>ggfgg</ns2:nome>
                    <ns2:sobrenome>ccg</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>djfbf@gmail.com </ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1310</ns2:id>
                <ns2:idUser>2820</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2820</ns2:id>
                    <ns2:nome>deu</ns2:nome>
                    <ns2:sobrenome>certo</ns2:sobrenome>
                    <ns2:genero>Feminino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>deucerto@gmail.com </ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1311</ns2:id>
                <ns2:idUser>2822</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2822</ns2:id>
                    <ns2:nome>agora</ns2:nome>
                    <ns2:sobrenome>sim</ns2:sobrenome>
                    <ns2:genero>Feminino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>agorasim@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1312</ns2:id>
                <ns2:idUser>2824</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2824</ns2:id>
                    <ns2:nome>outro</ns2:nome>
                    <ns2:sobrenome>teste</ns2:sobrenome>
                    <ns2:genero>Feminino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>outroteste@gmail.com </ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1313</ns2:id>
                <ns2:idUser>2825</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2825</ns2:id>
                    <ns2:nome>André</ns2:nome>
                    <ns2:sobrenome>ciclista</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>123456789</ns2:BI>
                    <ns2:email>u6@example.com</ns2:email>
                    <ns2:telefone>+5511999999999</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1314</ns2:id>
                <ns2:idUser>2826</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2826</ns2:id>
                    <ns2:nome>hdheh</ns2:nome>
                    <ns2:sobrenome>jejehe</ns2:sobrenome>
                    <ns2:genero>Feminino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>jejej@gmail.com </ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1352</ns2:id>
                <ns2:idUser>2852</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2852</ns2:id>
                    <ns2:nome>ggg</ns2:nome>
                    <ns2:sobrenome>hhjj</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>gg@gmail.com </ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1402</ns2:id>
                <ns2:idUser>2902</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2902</ns2:id>
                    <ns2:nome>ugfe</ns2:nome>
                    <ns2:sobrenome>der</ns2:sobrenome>
                    <ns2:genero>Feminino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>ffh@gmail.com </ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1452</ns2:id>
                <ns2:idUser>2952</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>2952</ns2:id>
                    <ns2:nome>André</ns2:nome>
                    <ns2:sobrenome>ciclista</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>123456789</ns2:BI>
                    <ns2:email>u7@example.com</ns2:email>
                    <ns2:telefone>+5511999999999</ns2:telefone>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1502</ns2:id>
                <ns2:idUser>3002</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>3002</ns2:id>
                    <ns2:nome>gg</ns2:nome>
                    <ns2:sobrenome>qqw</ns2:sobrenome>
                    <ns2:genero>Feminino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>u7@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1552</ns2:id>
                <ns2:idUser>3053</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>3053</ns2:id>
                    <ns2:nome>tttdxdddu</ns2:nome>
                    <ns2:sobrenome>qqq</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>a2@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1553</ns2:id>
                <ns2:idUser>3054</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>3054</ns2:id>
                    <ns2:nome>tttdxdddu</ns2:nome>
                    <ns2:sobrenome>qqq</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>aef2@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1554</ns2:id>
                <ns2:idUser>3055</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>3055</ns2:id>
                    <ns2:nome>tttdxdddu</ns2:nome>
                    <ns2:sobrenome>qqq</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>aef@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1555</ns2:id>
                <ns2:idUser>3056</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>3056</ns2:id>
                    <ns2:nome>tttdxdddu</ns2:nome>
                    <ns2:sobrenome>qqq</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>ae23edf@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1556</ns2:id>
                <ns2:idUser>3057</ns2:idUser>
                <ns2:saldo>10.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>3057</ns2:id>
                    <ns2:nome>ja</ns2:nome>
                    <ns2:sobrenome>deu</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>ada@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>false</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
            <ns2:ciclistas>
                <ns2:id>1557</ns2:id>
                <ns2:idUser>3058</ns2:idUser>
                <ns2:saldo>9.0</ns2:saldo>
                <ns2:dadosUser>
                    <ns2:id>3058</ns2:id>
                    <ns2:nome>Andre</ns2:nome>
                    <ns2:sobrenome>Lubambi</ns2:sobrenome>
                    <ns2:genero>Masculino</ns2:genero>
                    <ns2:BI>132433hj43</ns2:BI>
                    <ns2:email>af@gmail.com</ns2:email>
                    <ns2:foto/>
                    <ns2:tipo>1</ns2:tipo>
                </ns2:dadosUser>
                <ns2:isDevedor>true</ns2:isDevedor>
                <ns2:erro>false</ns2:erro>
            </ns2:ciclistas>
        </ns2:GetAllCiclistasResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

`

export const allEstações = `
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:AllDocasResponse xmlns:ns2="http://station.soap.xml">
            <ns2:erro>true</ns2:erro>
            <ns2:mensagem>Falha ao pesquisar as estações!! I/O error: Ligação recusada</ns2:mensagem>
            <ns2:estacoes>
                <ns2:estacao>
                    <ns2:id>1</ns2:id>
                    <ns2:nome>Estacao Central</ns2:nome>
                    <ns2:local>Kilamba</ns2:local>
                    <ns2:premio>50.0</ns2:premio>
                    <ns2:latitude>50.5</ns2:latitude>
                    <ns2:longitude>100.5999984741211</ns2:longitude>
                    <ns2:activeState>true</ns2:activeState>
                    <ns2:qtdDocasTotais>6</ns2:qtdDocasTotais>
                    <ns2:qtdDocasLivres>6</ns2:qtdDocasLivres>
                </ns2:estacao>
            </ns2:estacoes>
            <ns2:estacoes>
                <ns2:estacao>
                    <ns2:id>2</ns2:id>
                    <ns2:nome>Estação Camama 1</ns2:nome>
                    <ns2:local>Camama 1</ns2:local>
                    <ns2:premio>20.0</ns2:premio>
                    <ns2:latitude>20.219999313354492</ns2:latitude>
                    <ns2:longitude>50.209999084472656</ns2:longitude>
                    <ns2:activeState>true</ns2:activeState>
                    <ns2:qtdDocasTotais>2</ns2:qtdDocasTotais>
                    <ns2:qtdDocasLivres>2</ns2:qtdDocasLivres>
                </ns2:estacao>
            </ns2:estacoes>
        </ns2:AllDocasResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`

export const estacaoDetail = `
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:GetStationDetailsResponse xmlns:ns2="http://station.soap.xml">
            <ns2:estado>true</ns2:estado>
            <ns2:mensagem>Estação encontrada com sucesso!!!</ns2:mensagem>
            <ns2:dadosEstacao>
                <ns2:id>1</ns2:id>
                <ns2:nome>Estacao Central</ns2:nome>
                <ns2:local>Kilamba</ns2:local>
                <ns2:premio>50.0</ns2:premio>
                <ns2:latitude>50.5</ns2:latitude>
                <ns2:longitude>100.5999984741211</ns2:longitude>
                <ns2:activeState>true</ns2:activeState>
                <ns2:qtdDocasTotais>6</ns2:qtdDocasTotais>
                <ns2:qtdDocasLivres>6</ns2:qtdDocasLivres>
            </ns2:dadosEstacao>
        </ns2:GetStationDetailsResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`
export const allDoca = `
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:AllDocasResponse xmlns:ns2="http://station.soap.xml">
            <ns2:erro>false</ns2:erro>
            <ns2:mensagem>Docas carregadas com sucesso!</ns2:mensagem>
            <ns2:TodasDocas>
                <ns2:id>202</ns2:id>
                <ns2:reference>DCE01N001</ns2:reference>
                <ns2:aberta>true</ns2:aberta>
                <ns2:sinal/>
            </ns2:TodasDocas>
            <ns2:TodasDocas>
                <ns2:id>203</ns2:id>
                <ns2:reference>DCE01N011</ns2:reference>
                <ns2:aberta>true</ns2:aberta>
                <ns2:sinal>2F234454-CF6D-4A0F-ADF2-F4911BA9FFA6</ns2:sinal>
            </ns2:TodasDocas>
            <ns2:TodasDocas>
                <ns2:id>204</ns2:id>
                <ns2:reference>DCE01N021</ns2:reference>
                <ns2:aberta>true</ns2:aberta>
            </ns2:TodasDocas>
            <ns2:TodasDocas>
                <ns2:id>252</ns2:id>
                <ns2:reference>DCE01N031</ns2:reference>
                <ns2:aberta>true</ns2:aberta>
            </ns2:TodasDocas>
            <ns2:TodasDocas>
                <ns2:id>253</ns2:id>
                <ns2:reference>DCE01N041</ns2:reference>
                <ns2:aberta>true</ns2:aberta>
            </ns2:TodasDocas>
            <ns2:TodasDocas>
                <ns2:id>254</ns2:id>
                <ns2:reference>DCE01N051</ns2:reference>
                <ns2:aberta>true</ns2:aberta>
            </ns2:TodasDocas>
            <ns2:TodasDocas>
                <ns2:id>255</ns2:id>
                <ns2:reference>DCE01N061</ns2:reference>
                <ns2:aberta>true</ns2:aberta>
            </ns2:TodasDocas>
        </ns2:AllDocasResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`

export const addDoca = `
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:AllDocasResponse xmlns:ns2="http://station.soap.xml">
            <ns2:erro>false</ns2:erro>
            <ns2:mensagem>Nova doca adiconada com sucesso!</ns2:mensagem>
            <ns2:dadosDoca>
                <ns2:id>54</ns2:id>
                <ns2:reference>DCE02N041</ns2:reference>
                <ns2:aberta>true</ns2:aberta>
            </ns2:dadosDoca>
        </ns2:AllDocasResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

export const allResser = `
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:GetAllReservaResponse xmlns:ns2="http://station.soap.xml">
            <ns2:erro>false</ns2:erro>
            <ns2:mensagem>Sucesso ao pegar as reservas de uma estação</ns2:mensagem>
            <ns2:TodasReservas>
                <ns2:erro>false</ns2:erro>
                <ns2:id>403</ns2:id>
                <ns2:idUser>1</ns2:idUser>
                <ns2:idEstacao>1</ns2:idEstacao>
                <ns2:idDoca>3</ns2:idDoca>
            </ns2:TodasReservas>
            <ns2:TodasReservas>
                <ns2:erro>false</ns2:erro>
                <ns2:id>403</ns2:id>
                <ns2:idUser>1</ns2:idUser>
                <ns2:idEstacao>1</ns2:idEstacao>
                <ns2:idDoca>3</ns2:idDoca>
            </ns2:TodasReservas>
        </ns2:GetAllReservaResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`

export const newAdmin = `
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:UserGestorResponse xmlns:ns2="http://user.soap.xml">
            <ns2:id>752</ns2:id>
            <ns2:idUser>3102</ns2:idUser>
            <ns2:idEstacao>1</ns2:idEstacao>
            <ns2:dadosUser>
                <ns2:id>3102</ns2:id>
                <ns2:password>240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9</ns2:password>
                <ns2:nome>Sillk</ns2:nome>
                <ns2:sobrenome>Manuel</ns2:sobrenome>
                <ns2:genero>Masculino</ns2:genero>
                <ns2:BI>001456237</ns2:BI>
                <ns2:email>silk@bs.com</ns2:email>
                <ns2:telefone>99999999</ns2:telefone>
                <ns2:foto/>
                <ns2:tipo>2</ns2:tipo>
            </ns2:dadosUser>
            <ns2:erro>false</ns2:erro>
            <ns2:mensagem>Usuário Administrativo adicionado com sucesso!!!</ns2:mensagem>
        </ns2:UserGestorResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`